"use strict";
var postText = [
	"Computer Mainframe Operating System",
	"Version 1.3.3.7",
	"Copyright (C) 198X",
	"Seattle Computing",
	"Allied Microsystems Software, Inc.",
	"All wrongs reserved.",
	"--------------------------------------------",
	"CPU Architecture: 16-BIT", 
	"Clock Speed: 23647HZ", 
	"Memory: 64Kb OK",
	"MEMCHK16 BEGIN",
];
var startupText = [
	"INITIALIZING M.OS MAINTENANCE MODE",
	"--------------------------------------------",
	"Running startup scripts",
	"Begin software authenticity check",
	"Computing CRC sums..........................",
	"............................................",
	"............................................",
	"............................................",
	"............................................",
	"............................................",
	".......................",
];
export const prerollText = { 
	post:postText,
	memcheck:postText.concat([
		"MEMORY ERROR AT SECTOR 0X00000000",
		"MEMORY ERROR AT SECTOR 0X00000001",
		"MEMORY ERROR AT SECTOR 0X00000003",
		"MEMORY ERROR AT SECTOR 0X00000007",
		"MEMORY ERROR AT SECTOR 0X0000000F",
		"MEMORY ERROR AT SECTOR 0X0000002C",
		"MEMORY ERROR AT SECTOR 0X0000004D",
		"MEMORY ERROR AT SECTOR 0X00000077",
		"MEMORY ERROR AT SECTOR 0X000001A1",
		"MEMORY ERROR AT SECTOR 0X0000026F",
		"MEMORY ERROR AT SECTOR 0X00000300",
		"MEMORY ERROR AT SECTOR 0X000007C3",
		"MEMORY ERROR AT SECTOR 0X00000F24",
		"MEMORY ERROR AT SECTOR 0X000010A1",
		"MEMORY ERROR AT SECTOR 0XDEADBEEF",
		"ERROR: MEMORY ERROR THRESHOLD EXCEEDED",
		"ENTERING M.OS MAINTENANCE MODE",
	]),
	startup:startupText,
	errors:startupText.slice(0,-1).concat([
		"WARNING: UNAUTHORIZED BINARY AD4M.AI.......",
	]),
	overwrite:startupText.slice(0,-1).concat([
		"n0Th1Ng 2 C HeR3...........................",
	]),
	display:[
		"INITIALIZING M.OS MAINTENANCE MODE",
		"--------------------------------------------",
		"Calibrating Display.........................",
		"............................................",
		"............................................",
		"............................................",
		"Display OK",
	],
	dmi:[
		"INITIALIZING M.OS MAINTENANCE MODE",
		"--------------------------------------------",
		"Starting DMI (Direct Memory Interface)......",
		"Simulation Mode enabled.....................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"............................................",
		"....................",
	],
};
